### ISSUE TITLE
[Crash] Front Camera

### ISSUE THREAD

**Issue by orangemechanic** [brownemint/Ti-Android-CameraView#4]
The module work fine when using the Rear Camera.
But if on creation I set useFrontCamera:true, then it just crashes.

----
LOG

[INFO] :   CameraViewProxy: (main) [21542,30155] Front Camera Property exists!
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 17.859MB for 2560016-byte allocation
[INFO] :   Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
[INFO] :   CameraViewProxy: (main) [572,30727] Opening Camera
[INFO] :   Camera: sendBroadcast intent.stop.app-in-app
[INFO] :   CameraViewProxy: (main) [95,30822] Setting Preview Display
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41cb22a0)
[INFO] :   Process: Sending signal. PID: 10785 SIG: 9

**Comment by brownemint** [comment]
Thanks for bringing this to my attention. The issue is due to the front camera not having support for auto focus. This seems to be particular to some devices and never came up in my testing.

0.6 of the module (in the dist folder) contains the fix for this. I've testing it on a Galaxy S2. Could you verify it yourself before I close the issue?

**Comment by orangemechanic** [comment]
FIXED. Thank you
